version: '3.8'

services:
  db_erp:
    image: postgres:15
    container_name: odoo_erp_basic_db
    environment:
      POSTGRES_DB: odoo_erp_basic
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - db_data_erp:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 10s
      timeout: 5s
      retries: 5

  odoo_erp:
    image: odoo:17
    container_name: odoo_erp_basic
    depends_on:
      db_erp:
        condition: service_healthy
    environment:
      HOST: db_erp
      USER: odoo
      PASSWORD: odoo
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
    command: -c /etc/odoo/odoo.conf

volumes:
  db_data_erp:
