[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
admin_passwd = admin
db_host = db_erp
db_maxconn = 64
db_name = odoo_erp_basic
db_password = odoo
db_port = 5432
db_sslmode = prefer
db_template = template0
db_user = odoo
dbfilter = ^odoo_erp_basic$
demo = {}
email_from = noreply@example.com
geoip_database = /usr/share/GeoIP/GeoLite2-City.mmdb
http_interface = 0.0.0.0
http_port = 8069
import_partial = 
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 60
limit_time_real = 120
list_db = True
log_db = False
log_handler = :INFO
logfile = /var/log/odoo/odoo.log
logrotate = 1
max_cron_threads = 2
osv_memory_age_limit = 1.0
osv_memory_count_limit = False
pg_path = /usr/lib/postgresql/15/bin
pidfile = None
proxy_mode = False
reportgz = False
secure_cert_file = server.cert
secure_key_file = server.key
server_wide_modules = base,web
smtp_password = False
smtp_port = 25
smtp_server = localhost
smtp_ssl = False
smtp_user = False
syslog = False
test_enable = False
test_file = 
test_tags = None
translate_modules = ['all']
unaccent = False
upgrade_path = 
workers = 2
xmlrpc = True
xmlrpc_interface = 0.0.0.0
xmlrpc_port = 8069
xmlrpcs = True
xmlrpcs_interface = 0.0.0.0
xmlrpcs_port = 8070
